[project]
name = "url-shortener"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiosqlite>=0.22.1",
    "alembic>=1.18.2",
    "fastapi[standard]>=0.128.0",
    "greenlet>=3.3.1",
    "sqlalchemy>=2.0.46",
]
